"""Edit fields in Comment

Revision ID: 3e440363a69b
Revises: f7b41a8a38b0
Create Date: 2024-11-20 15:37:00.280196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e440363a69b'
down_revision: Union[str, None] = 'f7b41a8a38b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.Integer(), nullable=False))
    op.drop_constraint('comments_user_name_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('comments', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_name_fkey', 'comments', 'users', ['user_name'], ['username'], ondelete='CASCADE')
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###
