"""Edit fields in Post

Revision ID: f7b41a8a38b0
Revises: fc8539b9268b
Create Date: 2024-11-20 15:26:40.349025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b41a8a38b0'
down_revision: Union[str, None] = 'fc8539b9268b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(), nullable=False))
    op.add_column('posts', sa.Column('author', sa.Integer(), nullable=False))
    op.drop_constraint('posts_category_name_fkey', 'posts', type_='foreignkey')
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'posts', 'categories', ['category'], ['slug'])
    op.drop_column('posts', 'category_name')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('category_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('posts_category_name_fkey', 'posts', 'categories', ['category_name'], ['name'])
    op.drop_column('posts', 'author')
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
